### ISSUE TITLE
Unwanted autocompletion in certain situations

### ISSUE THREAD

**Issue by TimvdLippe** [robdodson/Atom-PolymerSnippets#14]
I really like the autocompletion, but in some scenarios it generates unwanted results:
1. When I am editing my css rules, the snippets almost always conflict of what I am typing. For example I am styling a `paper-card`, this snippet generates HTML code. I am not sure if this is inherent of the nature of Atom snippets, but maybe there is a possible solution.
2. Most of the time I type `<name-of-element` and then the autocompletion generates another start tag. Resulting in `<<name-of-element>...</name-of-element>`. Could this be added so the additional `<` is optional (with some sort of RegEx maybe?).

Hopefully these issues are solvable, else I will just have to deal with them ;p

**Comment by mateusortiz** [comment]
Thanks for reporting the problems and I will solve them :+1:

**Comment by TimvdLippe** [comment]
Continued to think about this. Maybe it would be best to force the `<` by default. This would deny the snippet to pop up during CSS editing AND solves the 2nd issue. It also makes the user force to import an element and not something else (could be the name in the docs too).

**Comment by jordanbtucker** [comment]
Item 1 is a pretty easy fix, even though [atom/language-html](https://github.com/atom/language-html) has this issue too. I just created a [PR to fix it in language-html (#86)](https://github.com/atom/language-html/pull/86).

I'm not sure about fixing item 2, but regarding forcing the `<` character, non-word characters in prefixes won't work with [autocomplete-snippets (see #56)](https://github.com/atom/autocomplete-snippets/issues/56), which is now a core package. I would wait on forcing `<` until a fix is implemented.

Non-word characters in prefixes do work, they just don't show up in the autocomplete list, so it will likely confuse users.

**Comment by TimvdLippe** [comment]
Hello @jordanbtucker ,

Thank you for your explanation. Looking at your PR at https://github.com/atom/language-html/pull/86 it seems that the custom element snippet `ce` still shows up within the `<script>`. Is there an additional fix needed for this repository?

I personally don't think it would confuse users, but I can only speak for myself ofc.

Thanks for your time.

**Comment by jordanbtucker** [comment]
The custom element snippet still shows up because the fix was for HTML snippets, not Polymer snippets. The same fix that was employed in that PR must be implemented in Polymer snippets.

**Comment by jordanbtucker** [comment]
Also, I just realized that the `ce` snippet is a JavaScript snippet, and therefore is showing up in the right place. However, non-JavaScript snippets, like `paper-element` are still showing up in the wrong place.

**Comment by TimvdLippe** [comment]
All right. I will wait for both PRs then. Thanks again!
