### ISSUE TITLE
Quotes in the incorrect place - iron-input snippet

### ISSUE THREAD

**Issue by WaverleyDesign** [robdodson/Atom-PolymerSnippets#22]
Using the iron-input snippet results in this for me:
<code>  `<input is="iron-input" bind-value={{myValue}}"">` </code>
Not sure why though - the .cson looks fine.

**Comment by mateusortiz** [comment]
I'm taking a look :mag:

**Comment by mateusortiz** [comment]
I found bug and already fixed.
Thanks @WaverleyDesign
