### ISSUE TITLE
Test Snippets 

### ISSUE THREAD

**Issue by BLamy** [robdodson/Atom-PolymerSnippets#30]
Both BDD and TDD sort of like the polymer generator. 

https://github.com/yeoman/generator-polymer/blob/master/el/templates/test/tdd.html

https://github.com/yeoman/generator-polymer/blob/master/el/templates/test/bdd.html

**Comment by mateusortiz** [comment]
Good tip, it was as expected?

**Comment by robdodson** [comment]
@BLamy hm do you think this could be covered by a separate Mocha package?

**Comment by mateusortiz** [comment]
@robdodson This looks good

**Comment by robdodson** [comment]
Oh I didn't realize this was being commited. @mateusortiz would you mind opening a pull request for future changes so we can discuss them?

**Comment by mateusortiz** [comment]
Yeap of course. Sorry!

**Comment by BLamy** [comment]
Can we change the shortcut for it from  `*-element` to  `bdd-test` and `tdd-test`.

The snippets aren't really 'elements'. I doubt it will make a difference as far as typing goes since most people will have hit tab before they get to that part.

**Comment by robdodson** [comment]
sure! I think there's also a couple spots where we can remove the scripts
for test-fixture because (I believe) that just comes with web component
tester now and doens't need a specific script/import

**Comment by TimvdLippe** [comment]
This issue was fixed in https://github.com/robdodson/Atom-PolymerSnippets/commit/685bc68de6393da8a76a110e390f486f5dcb655e and can be closed
