### ISSUE TITLE
Indentation Option

### ISSUE THREAD

**Issue by Aaron-Pool** [robdodson/Atom-PolymerSnippets#34]
Is there any way you can odd some sort of config to the plugin to make the indentation more than 2 spaces?

**Comment by mateusortiz** [comment]
The best way is editing the indentation of file is on directory of atom configs snippets. 

_explain gif_:

![Imgur](http://i.imgur.com/4kvK9wu.gif)

**Comment by robdodson** [comment]
We should check if the snippets are using tabs or spaces. I know Sublime will replace tabs with whatever your preferred indentation is but it won't do it for spaces. I wonder if there's a similar setup for Atom

**Comment by mateusortiz** [comment]
This? [EditorConfig Atom](https://github.com/sindresorhus/atom-editorconfig)

**Comment by Aaron-Pool** [comment]
@mateusortiz Thanks! I can do that. Though, for future reference, I can imagine this would be substantially more convenient as a config option, if possible.

**Comment by robdodson** [comment]
I'll check if we're using spaces or tabs. You shouldn't need editorconfig

**Comment by Aaron-Pool** [comment]
Thanks Rob!

**Comment by robdodson** [comment]
@Aaron-Pool can you do me a favor?

There are two snippets I'd like you to try in a fresh html file.

The first is `pefs` and the second is `pe`. I _think_ `pefs` should give you the indentation you want, whereas `pe` will always do 2 levels of spaces. Can you verify this? The difference is I noticed that `pefs` is using tabs throughout and I believe Atom will convert those to match whatever your preferences are.

**Comment by Aaron-Pool** [comment]
I'll do my best to try them out ASAP.

**Comment by Aaron-Pool** [comment]
@robdodson That did the trick, thanks! I did a double check and can't seem to find that in the main project writeup, did I miss it, or is it not there?

**Comment by robdodson** [comment]
@Aaron-Pool I think it's just the way Sublime and Atom work. If you use tabs for indentation it'll swap them out for user preference but it won't do it for spaces. I guess that means we need to go through and convert all the snippets to tabs :P

**Comment by Aaron-Pool** [comment]
@robdodson The old space/tabs paradigm, biting developers since the dawn of time. Oh well, thanks for the quick follow up, and I'll stick with `pefs` for now.

**Comment by TimvdLippe** [comment]
Closing per #47.
