### ISSUE TITLE
Publish release to be able to update from Atom

### ISSUE THREAD

**Issue by TimvdLippe** [robdodson/Atom-PolymerSnippets#35]
The latest master includes several snippets I would like to use (the tdd-test for example), but the latest release is from December 2015. Atom therefore does not detect that there was an update of this package and I can not use the new goodies </3. Could you publish a release for latest master?

**Comment by robdodson** [comment]
@TimvdLippe oh sure! btw do you want to be added as a co-maintainer?

**Comment by TimvdLippe** [comment]
Yes sure! Shall we discuss on Slack about the specifics?

**Comment by robdodson** [comment]
Sure. But I'm going to go ahead and add you as a maintainer so you can review/merge PRs and stuff.

**Comment by robdodson** [comment]
@TimvdLippe I just used apm to publish a new version... I think it worked? Can you check?

**Comment by TimvdLippe** [comment]
Yes it worked :tada:
