### ISSUE TITLE
Add snippets for new elements

### ISSUE THREAD

**Issue by TimvdLippe** [robdodson/Atom-PolymerSnippets#36]
- [x] `app-location`
- [x] `app-route`
- [ ] `app-toolbar`
- [ ] `app-header`
- [ ] `app-header-layout`
- [ ] `app-drawer`
- [ ] `app-drawer-layout`
- [ ] `app-box`
- [ ] `app-scrollpos-control`

**Comment by LukeMoll** [comment]
*bump*
I noticed the `platinum-*` elements are missing snippets, should this be added to this issue ("new" elements) or made into a new issue? I'd be happy to have a go at writing some

**Comment by robdodson** [comment]
The plantinum elements are probably on their way to being deprecated.

@tjsavage we should probably put up a sign saying this. Who would be the right person to handle that?

**Comment by LukeMoll** [comment]
That's a shame - I was just about to add offline to my PWA. What should I be using instead, vanilla SW JavaScript?

**Comment by robdodson** [comment]
Yeah you can take a look at the service worker setup in polymer starter kit
https://github.com/PolymerElements/polymer-starter-kit which uses polymer
CLI to generate a service worker based on a config file. Or you can look at
the setup used in generator-polymer-init-custom-build

**Comment by LukeMoll** [comment]
Are there any plans for future elements with a similar functionality or has it been decided that they're two things that should not mix?

**Comment by robdodson** [comment]
Probably not in the near term. In the long run, who knows 😀

**Comment by LukeMoll** [comment]
Alright, thanks anyway!

**Comment by TimvdLippe** [comment]
Closing this in favor of the Polymer editor services, which are more complete and maintainable 🎉
