### ISSUE TITLE
Documentation update, at least Atom 1.8.0 requires a restart for this feature to work

### ISSUE THREAD

**Issue by pbx9959** [robdodson/Atom-PolymerSnippets#38]
Requires restart of Atom

**Comment by TimvdLippe** [comment]
Could you elaborate a bit more (preferably with reproduction steps) on the issue? At this point I am not sure what is not working for you.

**Comment by pbx9959** [comment]
Just saying to elaborate on the documentation page. When I installed it on Atom 1.8.0 I needed to restart Atom for it to be able to be used, didnt see that step in the installation part.
