### ISSUE TITLE
Disable Snippets while inside a tag

### ISSUE THREAD

**Issue by nklayman** [robdodson/Atom-PolymerSnippets#45]
If you create a snippet with the same name and prefix as a tag snippet with no body that's scope is set to inside a <tag>, then it will effectively disable the snippet when the cursor is inside a tag. This will prevent Snippets from showing up when you are editing attributes. I will create a PR with these changes as soon as I can.

![image](https://cloud.githubusercontent.com/assets/12448243/26270676/d2549f58-3cb1-11e7-9296-67c85ff18d1b.png)

![snippet_fix](https://cloud.githubusercontent.com/assets/12448243/26270843/6948d81a-3cb3-11e7-8475-635e017df481.gif)

**Comment by TimvdLippe** [comment]
Closing per #47.
