### ISSUE TITLE
Tab completion isn't working

### ISSUE THREAD

**Issue by robdodson** [robdodson/Atom-PolymerSnippets#5]
I noticed today that if I have Emmet installed, it will clobber tab completion inside of HTML files. [Here's a workaround](https://github.com/emmetio/emmet-atom/issues/225#issuecomment-82669798).

**Comment by jordanbtucker** [comment]
Thanks for the mention. I just updated the workaround with some more information regarding Emmet expansions inside snippets.

**Comment by robdodson** [comment]
awesome thank you!
