### ISSUE TITLE
Polymer version 1.0

### ISSUE THREAD

**Issue by bvhme** [robdodson/Atom-PolymerSnippets#9]
Hey, are there any plans or ideas to make a PolymerSnippets for Polymer 1.0 and it's changed API? I'm offering my help but I'm a bit of an amateur. Thanks

**Comment by mateusortiz** [comment]
Hey @bvhme, first we will update Polymer snippets for Sublime, and then upgrade to the atom. Thks

**Comment by abdonrd** [comment]
+1
I offer my help too!

**Comment by robdodson** [comment]
@mateusortiz is working on it: https://github.com/robdodson/Atom-PolymerSnippets/pull/10 There are a few minor things that still need to be fixed but the PR should be merged soon

**Comment by mateusortiz** [comment]
Gracias @abdonrd, I have repaired the things, but we accept all the help.

**Comment by bvhme** [comment]
Awesome, I love it, the PR looks good, even the `script` is inside the `dom-module`

Excited to see this merged, convinced it will be good.
